version: "3.8"

services:
  db:
    image: postgres:14
    container_name: mydb
    environment:
      POSTGRES_USER:   postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:     mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U example_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
